### ISSUE TITLE
注册方法的user结构体赋值错误了，导致登录的时候会验证密码失败。

### ISSUE THREAD

**Issue by sanpangzi424** [sun-wenming/gin-auth#1]
**改成：userService := userser.User{UserName: mAuth.UserName, Password: mAuth.Password**

源码：
func Register(c *gin.Context) {
	appG := app.GetGin(c)
	var mAuth auth

	// 解析 body json 数据到实体类
	if err := c.ShouldBindJSON(&mAuth); err != nil {
		appG.ResponseFailError(util.ErrNewErr(err))
		return
	}
	// 验证
	validate := util.GetValidate()
	err := validate.Struct(mAuth)
	if err != nil {
		appG.ResponseFailValidParam(err)
		return
	}

	userService := userser.User{UserName: mAuth.UserName, Password: mAuth.UserName}

**Comment by sun-wenming** [comment]
已更改，抱歉许久未看到此消息。
